// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	integrationloader "github.com/sensu/catalog-api/internal/integrationloader"
	mock "github.com/stretchr/testify/mock"

	types "github.com/sensu/catalog-api/internal/types"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

// LoadIntegrations provides a mock function with given fields:
func (_m *Loader) LoadIntegrations() (types.Integrations, error) {
	ret := _m.Called()

	var r0 types.Integrations
	if rf, ok := ret.Get(0).(func() types.Integrations); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Integrations)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIntegrationLoader provides a mock function with given fields: integration
func (_m *Loader) NewIntegrationLoader(integration types.IntegrationVersion) integrationloader.Loader {
	ret := _m.Called(integration)

	var r0 integrationloader.Loader
	if rf, ok := ret.Get(0).(func(types.IntegrationVersion) integrationloader.Loader); ok {
		r0 = rf(integration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(integrationloader.Loader)
		}
	}

	return r0
}
